---

# https://bugs.launchpad.net/cloud-init/+bug/1541196

- name: 'systemd unit file templated for cloud-init log file permissions control'
  template:
    src: 'cloud-init-log-permissions.service.j2'
    dest: '/etc/systemd/system/cloud-init-log-permissions.service'

- name: 'service started for cloud-init log file permissions control'
  systemd:
    name: 'cloud-init-log-permissions.service'
    daemon_reload: 'yes'
    enabled: 'yes'
    state: 'started'