---

- name: 'operating system-specific variables imported'
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

# https://bugs.launchpad.net/cloud-init/+bug/1541196

- name: 'systemd unit file templated for cloud-init log file permissions control'
  template:
    src: 'cloud-init-log-permissions.service.j2'
    dest: '/etc/systemd/system/cloud-init-log-permissions.service'

- name: 'service started for cloud-init log file permissions control'
  systemd:
    name: 'cloud-init-log-permissions.service'
    daemon_reload: 'yes'
    enabled: 'yes'
    state: 'started'