---

- name: 'list of words copied into place'
  copy:
    src: 'words'
    dest: '/opt/words'

- name: 'password generated'
  shell: "cat /opt/words | shuf --random-source=/dev/urandom --head-count 11 | paste --delimiters=' ' --serial | head -c -1"
  register: 'exouser_password_cmd'
  check_mode: false
  no_log: true

- name: 'password saved as variable'
  set_fact:
    exouser_password: '{{ exouser_password_cmd.stdout }}'
  no_log: true

- name: 'password POSTed to OpenStack metadata service'
  command: 'curl --fail --silent --request POST {{ password_post_url }} --data "{{ exouser_password }}"'
  no_log: true

- name: 'password set for exouser'
  user:
    name: 'exouser'
    password: "{{ exouser_password | password_hash('sha512') }}"
  no_log: true
