image: node:4.2.2

stages:
  - build
  - test
  - deploy

elm_make:
  stage: build
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install -g elm
    - elm-package install -y
  script:
    - elm make --warn --yes src/Exosphere.elm --output public/index.html
  artifacts:
    paths:
      - public

elm_analyse:
  stage: test
  cache:
    paths:
      - elm-stuff/
  before_script:
    - npm install -g elm elm-analyse elm-format
    - elm-package install -y
  script:
    - elm-analyse || true

elm_test:
  stage: test
  cache:
    paths:
      - tests/elm-stuff/build-artifacts
  before_script:
    - npm install -g elm elm-test@beta
  script:
    - elm-test

pages:
  stage: deploy
  dependencies:
    - elm_make
  script:
    - file public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
