image: node:current-buster

stages:
  - build
# temporarily disabled
#  - dockerize
#  - test
#  - deploy

cache:
  key: ${CI_JOB_NAME}
  paths:
    - node_modules/
    - home/.elm
    - home/.npm
    - elm-stuff/

.build_with_kaniko:
  #Hidden job to use as an "extends" template
  stage: dockerize
  needs:
    - elm_make
  allow_failure: true
  retry: 1
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - cp public/elm-web.js .
    - cp public/ports.js .
    - cp public/config.js .
  script:
    - BROWSER_LOWER="$(echo $BROWSER | tr '[:upper:]' '[:lower:]')"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - |
      TAGLIST="$CI_COMMIT_REF_NAME $CI_COMMIT_SHORT_SHA $CI_COMMIT_BRANCH"
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then TAGLIST="$TAGLIST latest"; fi
      if [[ -n "$TAGLIST" ]]; then
        for TAG in $TAGLIST; do
          FORMATTEDTAGLIST="${FORMATTEDTAGLIST} --destination $CI_REGISTRY_IMAGE:e2e-${BROWSER_LOWER}-$TAG ";
        done;
      fi
      DOCKER_FILE="$CI_PROJECT_DIR/integration-tests/docker/Selenium${BROWSER}AndExosphere/Dockerfile"
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $DOCKER_FILE $FORMATTEDTAGLIST


build_with_kaniko_e2e_firefox:
  extends: .build_with_kaniko
  variables:
    BROWSER: "Firefox"


build_with_kaniko_e2e_chrome:
  extends: .build_with_kaniko
  variables:
    BROWSER: "Chrome"


elm_make:
  stage: build
  before_script:
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/327#note_225643576
    - if [ -d home/.elm ]; then echo "Restoring ~/.elm"; mv home/.elm ~/; fi
    - if [ -d home/.npm ]; then echo "Restoring ~/.npm"; mv home/.npm ~/; fi
    - npm install elm@0.19.1-3
  script:
    - npx elm make src/Exosphere.elm --output public/elm-web.js
    - npx elm make src/ExosphereElectron.elm --output public/elm.js
    - cp index.html public/index.html
    - cp ports.js public/ports.js
    - cp config.js public/config.js
    - cp exosphere.webmanifest public
    - cp -R assets public
    - cp -R fonts public
    - cp service-worker.js public
    - md5sum public/index.html public/elm-web.js public/ports.js public/config.js
  after_script:
    - mkdir -p home && mv ~/.elm home
    - mkdir -p home && mv ~/.npm home
  artifacts:
    paths:
      - public

elm_analyse:
  stage: test
  needs:
    - elm_make
  before_script:
    - if [ -d home/.elm ]; then echo "Restoring ~/.elm"; mv home/.elm ~/; fi
    - if [ -d home/.npm ]; then echo "Restoring ~/.npm"; mv home/.npm ~/; fi
    - npm install elm@0.19.1-3 elm-analyse elm-format
  script:
    - npx elm-analyse
    - npx elm-format --validate src
  after_script:
    - mkdir -p home && mv ~/.elm home
    - mkdir -p home && mv ~/.npm home

elm_test:
  stage: test
  needs:
    - elm_make
  before_script:
    - if [ -d home/.elm ]; then echo "Restoring ~/.elm"; mv home/.elm ~/; fi
    - if [ -d home/.npm ]; then echo "Restoring ~/.npm"; mv home/.npm ~/; fi
    - npm install elm@0.19.1-3 elm-test@0.19.1
  script:
    - npx elm-test
    - npx elm-test --report junit > elm-test-report.xml
  after_script:
    - mkdir -p home && mv ~/.elm home
    - mkdir -p home && mv ~/.npm home
  artifacts:
    when: always
    reports:
      junit: elm-test-report.xml

pages:
  stage: deploy
  dependencies:
    - elm_make
  script:
    - touch public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

deploy_prod:
  stage: deploy
  resource_group: deploy_prod
  dependencies:
    - elm_make
  before_script:
    # See https://docs.gitlab.com/ee/ci/ssh_keys/README.html
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DOGFOOD_SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # https://docs.gitlab.com/ee/ci/ssh_keys/README.html#verifying-the-ssh-host-keys
    - echo "$DOGFOOD_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
  script:
    - 'cp environment-configs/try.exosphere.app-config.js public/config.js'
    - 'sed -i -e ''s/<base href="\/">/<base href="\/exosphere\/">/g'' public/index.html'
    - 'rsync -av --delete public exouser@dogfood.exosphere.app:'
  environment:
    name: prod
    url: https://try.exosphere.app/exosphere
  only:
    - master

deploy_jetstream:
  stage: deploy
  resource_group: deploy_jetstream
  dependencies:
    - elm_make
  before_script:
    # See https://docs.gitlab.com/ee/ci/ssh_keys/README.html
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DOGFOOD_SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # https://docs.gitlab.com/ee/ci/ssh_keys/README.html#verifying-the-ssh-host-keys
    - echo "$DOGFOOD_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
  script:
    - 'cp environment-configs/exosphere.jetstream-cloud.org-config.js public/config.js'
    - 'sed -i -e ''s/<base href="\/">/<base href="\/exosphere\/">/g'' public/index.html'
    - 'rsync -av --delete public exouser@dogfood.exosphere.app:jetstream-deploy/'
  environment:
    name: jetstream
    url: https://exosphere.jetstream-cloud.org/exosphere
  only:
    - master


deploy_dev:
  stage: deploy
  resource_group: deploy_dev
  needs:
    - elm_make
  before_script:
    # See https://docs.gitlab.com/ee/ci/ssh_keys/README.html
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DOGFOOD_SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # https://docs.gitlab.com/ee/ci/ssh_keys/README.html#verifying-the-ssh-host-keys
    - echo "$DOGFOOD_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
  script:
    - 'cp environment-configs/try-dev.exosphere.app-config.js public/config.js'
    - 'sed -i -e ''s/<base href="\/">/<base href="\/exosphere\/">/g'' public/index.html'
    - 'rsync -av --delete public exouser@dogfood.exosphere.app:dev-deploy/'
  environment:
    name: dev
    url: https://try-dev.exosphere.app/exosphere
  only:
    - dev

.e2e:
  #Hidden job to use as an "extends" template
  stage: test
  resource_group: e2e_iu_openstack
  image: python:3
  allow_failure: true
  retry: 1
  services:
    - name: "$CI_REGISTRY_IMAGE:e2e-${BROWSER_LOWER}-$CI_COMMIT_BRANCH"
      alias: e2e.exosphere.service
  before_script:
    - if [[ -z "$taccusername" || -z "$taccpass" ]]; then echo "Must provide taccusername and taccpass in environment" 1>&2; exit 1; fi
    - echo -e "section_start:`date +%s`:pip_install[collapsed=true]\r\e[0KInstall Python dependencies"
    - pip install -r integration-tests/requirements.txt
    - echo -e "section_end:`date +%s`:pip_install\r\e[0K"
    - mkdir -p integration-tests/screenshots integration-tests/logs
    # For visual debugging of browser via VNC, uncomment lines below to enable cloudflared tunnel:
#    - echo -e "section_start:`date +%s`:install_cloudflared[collapsed=true]\r\e[0KInstall cloudflared"
#    - wget -O ~/cloudflared.deb https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb
#    - dpkg -i ~/cloudflared.deb
#    - echo -e "section_end:`date +%s`:install_cloudflared\r\e[0K"
#    - echo -e "section_start:`date +%s`:cloudflared_tunnel_vnc[collapsed=true]\r\e[0KEstablish a Cloudflare tunnel to VNC"
#    - ./integration-tests/docker/run-cloudflared-tunnel.sh
#    - echo -e "section_end:`date +%s`:cloudflared_tunnel_vnc\r\e[0K"
#    - echo cloudflared should be running in the background. Sleep for 60 seconds so you can grab the VNC tunnel details.
#    - sleep 60
  script:
    - cd integration-tests
    - echo -e "section_start:`date +%s`:behave_run[collapsed=false]\r\e[0KRun behave"
    - behave --junit --no-skipped -D EXOSPHERE_BASE_URL=http://app.exosphere.localhost:8000 -D BROWSER=$BROWSER_LOWER -D REMOTE_WEBDRIVER=yes -D COMMAND_EXECUTOR=http://e2e.exosphere.service:4444/wd/hub features/exosphere.feature
    - echo -e "section_end:`date +%s`:behave_run\r\e[0K"
  artifacts:
    when: always
    reports:
      junit: integration-tests/reports/TESTS-exosphere.xml
    paths:
      - integration-tests/screenshots
      - integration-tests/logs

e2e_firefox:
  extends: .e2e
  variables:
    BROWSER_LOWER: "firefox"
  needs:
    - build_with_kaniko_e2e_firefox

e2e_chrome:
  extends: .e2e
  variables:
    BROWSER_LOWER: "chrome"
  needs:
    - build_with_kaniko_e2e_chrome

include:
  - template: Dependency-Scanning.gitlab-ci.yml
