---

cache:
  directories:
    - elm-stuff/build-artifacts
language: node_js
node_js:
  - node
before_script:
  - npm install -g elm elm-test elm-format elm-analyse
  - elm-package install -y
script:
    - elm-make --warn --yes src/Exosphere.elm --output elm.js
    - elm-analyse
    # - elm-test
