---

- name: 'xstartup templated'
  template:
    src: 'xstartup.j2'
    dest: '/home/{{ vnc_server_user }}/.vnc/xstartup'
    owner: '{{ vnc_server_user }}'

- name: 'systemd unit file templated'
  template:
    src: 'vncserver@.service.j2'
    dest: '/etc/systemd/system/vncserver@.service'

- name: 'systemd service enabled and started'
  systemd:
    name: 'vncserver@1.service'
    daemon_reload: 'yes'
    enabled: 'yes'
    state: 'started'
