---

- name: 'operating system-specific variables imported'
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: 'VNC server packages installed'
  package:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ vncserver_packages }}'

- name: 'user-specific VNC configuration directory created'
  file:
    path: '/home/{{ vnc_server_user }}/.vnc'
    state: 'directory'
    owner: '{{ vnc_server_user }}'

- name: 'VNC passphrase set'
  shell: 'echo "{{ exouser_passphrase }}" | vncpasswd -f > /home/{{ vnc_server_user }}/.vnc/passwd'
  no_log: true

- name: 'permissions set on VNC passphrase file'
  file:
    path: '/home/{{ vnc_server_user }}/.vnc/passwd'
    mode: '600'
    owner: '{{ vnc_server_user }}'

- name: 'configuration tasks imported for Ubuntu'
  import_tasks: 'configure-ubuntu.yml'
  when: 'ansible_distribution == "Ubuntu"'

- name: 'configuration tasks imported for RedHat-like'
  import_tasks: 'configure-rhel.yml'
  when: 'ansible_os_family == "RedHat"'
