---

- name: 'operating system-specific variables imported'
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Stop service unattended-upgrades
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    state: stopped

- name: Stop service apt-daily-upgrade.timer
  ansible.builtin.systemd_service:
    name: apt-daily-upgrade.timer
    state: stopped

- name: 'VNC server packages installed'
  package:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ vncserver_packages }}'

- name: Start service unattended-upgrades
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    state: started

- name: Start service apt-daily-upgrade.timer
  ansible.builtin.systemd_service:
    name: apt-daily-upgrade.timer
    state: started

- name: 'user-specific VNC configuration directory created'
  file:
    path: '/home/{{ vnc_server_user }}/.vnc'
    state: 'directory'
    owner: '{{ vnc_server_user }}'

- name: 'VNC passphrase set'
  shell: 'echo "{{ exouser_passphrase }}" | vncpasswd -f > /home/{{ vnc_server_user }}/.vnc/passwd'
  no_log: true

- name: 'permissions set on VNC passphrase file'
  file:
    path: '/home/{{ vnc_server_user }}/.vnc/passwd'
    mode: '600'
    owner: '{{ vnc_server_user }}'

- name: 'operating system specific tasks imported'
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/tasks"
