---

- name: 'system-wide VNC configuration directory created'
  file:
    path: '/etc/vnc'
    state: 'directory'

- name: 'xstartup templated for system'
  template:
    src: 'xstartup-system.j2'
    dest: '/etc/vnc/xstartup'
    mode: 'a+rx'

- name: 'xstartup templated for user'
  template:
    src: 'xstartup-user.j2'
    dest: '/home/{{ vnc_server_user }}/.vnc/xstartup'
    owner: '{{ vnc_server_user }}'
    mode: 'u+x'

- name: 'systemd unit file templated'
  template:
    src: 'vncserver@.service.j2'
    dest: '/etc/systemd/system/vncserver@.service'

- name: 'systemd service enabled and started'
  systemd:
    name: 'vncserver@1.service'
    daemon_reload: 'yes'
    enabled: 'yes'
    state: 'started'
