---

support_install_dir: "/opt/instance-config-support"

slicer_install_dir: "/media/volume/MyData"

slicer_version:
  major: 5
  minor: 9
  patch: 0

slicer_python_version: 3.9

# When updating the Slicer revision to >= 33807, make sure to remove the pinning of the "contourpy"
# package in "ansible/roles/slicer/files/slicer-install-extension-dependencies.py".

# slicer_release_id: "{{ slicer_version['major'] }}.{{ slicer_version['minor'] }}.{{ slicer_version['patch'] }}"
slicer_release_id: "33836"

slicer_extensions:
  - SlicerMorph
  - SurfaceWrapSolidify
  - PyTorch
  - Photogrammetry
  - MorphoDepot
  - NNInteractive  
