---

support_install_dir: "/opt/instance-config-support"

slicer_install_dir: "/media/volume/MyData"

slicer_version:
  major: 5
  minor: 7
  patch: 0

# slicer_release_id: "{{ slicer_version['major'] }}.{{ slicer_version['minor'] }}.{{ slicer_version['patch'] }}"
slicer_release_id: "33153"

slicer_extensions:
  - SlicerMorph
  - SurfaceWrapSolidify
