---

slicer_prerequisites_package_names:
  - 'libglu1-mesa'
  - 'libpulse-mainloop-glib0'
  - 'libnss3'
  - 'libasound2'
  - 'qt5dxcb-plugin'
  - 'libsm6'
  # Required by "slicer-download.sh"
  - 'jq'
