---

slicer_prerequisites_package_names:
  - 'libglu1-mesa'
  - 'libpulse-mainloop-glib0'
  - 'libnss3'
  - 'libasound2'
  - 'qt5dxcb-plugin'
  - 'libsm6'
  # Required by "slicer-download.sh"
  - 'curl'
  - 'jq'
  - 'rsync'
  # Required by R
  - 'tcllib'
  - 'tklib'
  # Required by R/devtools
  - 'libfreetype6-dev'
  - 'libfribidi-dev'
  - 'libharfbuzz-dev'
  - 'libjpeg-dev'
  - 'libjpeg-dev'
  - 'libpng-dev'
  - 'libtiff5-dev'
  - 'libxml2-dev'
  # NVIDIA
  # When using the "g3.xl" flavor, vGPU support is no longer needed. Therefore, we replace the default
  # "nvidia-linux-grid-535" driver with the more reliable "nvidia-driver-550-server-open".
  #
  # Currently, we do not have a mechanism to detect the exact flavor of the instance (e.g., g3.small, g3.medium, 
  # g3.large, g3.xl, m3.tiny, m3.small, etc.). As a temporary measure, we assume that the instance type is "g3.xl" 
  # and therefore always install "nvidia-driver-550-server-open".
  #
  # For additional context, refer to:
  # https://github.com/MorphoCloud/MorphoCloudWorkflow/issues/66
  - 'nvidia-driver-550-server-open'
