---

slicer_prerequisites_package_names:
  - 'libglu1-mesa'
  - 'libpulse-mainloop-glib0'
  - 'libnss3'
  - 'libasound2'
  - 'qt5dxcb-plugin'
  - 'libsm6'
  # Required by "slicer-download.sh"
  - 'curl'
  - 'jq'
  - 'rsync'
  # Required by R
  - 'tcllib'
  - 'tklib'
  # Required by R/devtools
  - 'libfreetype6-dev'
  - 'libfribidi-dev'
  - 'libharfbuzz-dev'
  - 'libjpeg-dev'
  - 'libjpeg-dev'
  - 'libpng-dev'
  - 'libtiff5-dev'
  - 'libxml2-dev'
  - 'libgl1-mesa-dev'
  - 'libglu1-mesa-dev'
