---

- name: 'tasks imported for CentOS'
  import_tasks: 'centos.yml'
  when: 'ansible_distribution == "CentOS"'

- name: 'tasks imported for Ubuntu'
  import_tasks: 'ubuntu.yml'
  when: 'ansible_distribution == "Ubuntu"'