---

- name: "python script copied"
  copy: 
    src: automount-volume.py
    dest: /usr/bin
    mode: 'u+rwx'
    owner: root
    
- name: "udev rules copied"
  copy:
    src: 99-exosphere-automount-volume.rules
    dest: /etc/udev/rules.d/

- name: "reload udev rules"
  shell: "udevadm control --reload-rules"

- name: "force trigger udev rules in case a volume was attached before ansible finished"
  shell: "udevadm trigger --action=add --sysname-match='[sv]d?'"
