- name: 'gnome-initial-setup-done touched to avoid startup dialog'
  file:
    path: '/etc/skel/.config/gnome-initial-setup-done'
    state: 'touch'
    mode: '0555'

- name: 'gnome-welcome-tour removed to avoid 2nd RHEL-specific dialog'
  file:
    path: '/etc/xdg/autostart/gnome-welcome-tour.desktop'
    state: 'absent'
