---

- name: 'operating system specific tasks imported'
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: 'Docker service started and enabled'
  systemd:
    name: 'docker'
    enabled: true
    state: 'started'

- name: 'exouser added to docker user group'
  user:
    name: 'exouser'
    append: 'yes'
    groups:
      - 'docker'