---

# May not be needed
# - name: 'yum-utils installed'
#   yum:
#     name: 'yum-utils'
#     state: 'present'

- name: 'Docker repository added'
  get_url:
    url: 'https://download.docker.com/linux/centos/docker-ce.repo'
    dest: '/etc/yum.repos.d/docker-ce.repo'

- name: 'Packages installed'
  yum:
    name:
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'containerd.io'
      - 'docker-compose-plugin'
    state: 'present'