---
- name: 'operating system-specific variables imported'
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: 'Slicer prerequisites installed'
  package:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ slicer_prerequisites_package_names }}'

- name: 'dist directory created'
  ansible.builtin.file:
    path: "{{ install_dir }}/dist"
    state: directory

#- name: 'helper script downloaded'
#  get_url:
#    url: "https://raw.githubusercontent.com/Slicer/SlicerDocker/e9353bd4e1b861c5fb78ac4cd90553696b119d22/scripts/slicer-download.sh"
#    dest: "{{ install_dir }}/dist/slicer-download.sh"
#    mode: "744"

- name: 'File "slicer-download.sh" copied'
  copy:
    src: 'slicer-download.sh'
    dest: "{{ install_dir }}/dist/slicer-download.sh"
    mode: "744"

- name: 'Slicer application installed'
  command: "{{ install_dir }}/dist/slicer-download.sh -d {{ install_dir }}/Slicer -v {{ slicer_release_id }} -s"

- name: 'File "Slicer.desktop" installed'
  copy:
    src: 'Slicer.desktop'
    dest: '/home/exouser/.config/xfce4/panel/launcher-21/Slicer.desktop'

- name: 'Placeholder "Slicer-X.Y" updated in file "Slicer.desktop"'
  ansible.builtin.replace:
    path: "/home/exouser/.config/xfce4/panel/launcher-21/Slicer.desktop"
    regexp: '(\s+)Slicer-X\.Y(\s+.*)?$'
    replace: '\1Slicer-{{ slicer_version["major"] }}.{{ slicer_version["minor"] }}\2'

- name: 'Slicer extensions installed'
  command: "{{ install_dir }}/dist/slicer-download.sh -d {{ install_dir }}/Slicer -v {{ slicer_release_id }} -e {{ item }}"
  loop: '{{ slicer_extensions }}'
